# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cvjGFOE9GbG62t2c9MiN9WbLZCAj57uK
"""

import pandas as pd
import inspect
from google.colab import files

data = {
    "Ism":["Shukurjon","Yusuf","Shomatjon"],
    "Familya":["Boqiyev","Zunnunov","Nishonov"],
    "Age":[21,21,22],
    "Region":["Ferghana","Ferghana","So'x"]
}

baza = pd.DataFrame(data)
print(baza)

baza.to_excel("talabalar.xlsx",index=False)
files.download("talabalar.xlsx")

age=baza[baza["Age"] == 21]
print(age)

tit = pd.read_csv('titanic.csv')

print(len(tit))

female = tit[tit['sex']=='female']
print(len(female))

female = tit[tit['age']<=18]
print(len(female))

female = tit[tit['home.dest'] == 'New York, NY']

print(len(female))